/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastriculas.ui;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import matriculas.entity.Universidad;
import matriculas.util.HibernateUtil;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * DAM. Curso 2024-2025 Módulo: Acceso a datos. Unidad 1: Mapeo Objeto
 * Relacional.
 *
 * @author Ana Rodríguez González
 * @version 1.0 Fecha: 27-01-2025
 *
 */
public class EliminarUniversidad extends javax.swing.JFrame {

    /**
     * Creates new form EliminarUniversidad
     */
    public EliminarUniversidad() {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAcept = new javax.swing.JButton();
        botonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spinnerCodigo = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAcept.setText("Aceptar");
        botonAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptActionPerformed(evt);
            }
        });

        botonCancel.setText("Cancelar");
        botonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar universidad por su código:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Indica el código de la universidad que deseas eliminar: ");

        spinnerCodigo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(spinnerCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAcept)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancel)
                    .addComponent(botonAcept))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelActionPerformed
        //Cerramos la ventana
        this.dispose();
    }//GEN-LAST:event_botonCancelActionPerformed

    private void botonAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptActionPerformed
        //Se ejecuta el método para eliminar la universidad
        eliminarUniversidad();
    }//GEN-LAST:event_botonAceptActionPerformed

    //  ////////////////////////////////////////////////////////////////   //
    //                         MÉTODOS DEL PROGRAMA                        //
    //  ////////////////////////////////////////////////////////////////   //
    //Método para eliminar la universidad según el código indicado en un spinner
    private void eliminarUniversidad() throws HibernateException, HeadlessException {
        Object valorSpinner = spinnerCodigo.getValue();
        Session session = null;
        Transaction transaction = null;
        try {

            session = HibernateUtil.getSessionFactory().openSession();
            transaction = session.beginTransaction();
            //Pasamos el valor del spinner a un entero
            int codigoUni = (int) valorSpinner;

            //Recuperamos de la base de datos la universidad que coincide con el código introducido en el spinner
            Universidad universidadBorrar = (Universidad) session.get(Universidad.class, codigoUni);

            if (universidadBorrar == null) {
                //Si no se encuentra la universidad, mostramos un mensaje y no intentamos eliminarla
                JOptionPane.showMessageDialog(this, "No existe ninguna universidad con el código " + codigoUni);
            } else if (universidadBorrar.getEstudiantes() != null && !universidadBorrar.getEstudiantes().isEmpty()) {
                //Si la universidad tiene estudiantes no se podrá eliminar
                JOptionPane.showMessageDialog(this, "No se puede eliminar una universidad con estudiantes matriculados");

            } else {
                //Eliminamos la universidad
                session.delete(universidadBorrar);
                transaction.commit(); //Confirmamos la transacción

                //Mostramos un mensaje al usuario
                JOptionPane.showMessageDialog(this, "La universidad con el código " + codigoUni + " ha sido eliminada correctamente.");
            }

        } catch (HibernateException he) {
            System.out.println("Error Hibernate: " + he.getMessage());
            if (transaction == null) {
                //Si hay algún error en la transacción
                //Hacemos un rollBack para deshacer los cambios
                transaction.rollback(); //Deshacemos los cambios
            }
            JOptionPane.showMessageDialog(this, "No se ha podido eliminar la universidad indicada.");
        } finally {
            if (session != null) {
                session.close();//Cerramos la sesión
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarUniversidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcept;
    private javax.swing.JButton botonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinnerCodigo;
    // End of variables declaration//GEN-END:variables
}
