/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastriculas.ui;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import matriculas.entity.Universidad;
import matriculas.util.HibernateUtil;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * DAM. Curso 2024-2025 Módulo: Acceso a datos. Unidad 1: Mapeo Objeto
 * Relacional.
 *
 * @author Ana Rodríguez González
 * @version 1.0 Fecha: 27-01-2025
 *
 */
public class NuevaUniversidad extends javax.swing.JFrame {

    /**
     * Creates new form NuevaUniversidad
     */
    public NuevaUniversidad() {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesPrivada = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoProvincia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        radioButtonSI = new javax.swing.JRadioButton();
        radioButtonNO = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        spinnerCodigo = new javax.swing.JSpinner();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Completa los campos para añadir una nueva Universidad: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabelNombre.setText("Nombre: ");

        jLabel2.setText("Provincia: ");

        jLabel3.setText("Privada: ");

        grupoBotonesPrivada.add(radioButtonSI);
        radioButtonSI.setText("SI");

        grupoBotonesPrivada.add(radioButtonNO);
        radioButtonNO.setText("NO");

        jLabel4.setText("Código: ");

        spinnerCodigo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 25, 1));

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonGuardar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(radioButtonSI)
                            .addGap(18, 18, 18)
                            .addComponent(radioButtonNO))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(spinnerCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCancelar)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioButtonSI)
                    .addComponent(radioButtonNO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        //Se ejecuta el método para guardar una universidad
        guardarUniversidad();
    }//GEN-LAST:event_botonGuardarActionPerformed

    //  ////////////////////////////////////////////////////////////////   //
    //                         MÉTODOS DEL PROGRAMA                        //
    //  ////////////////////////////////////////////////////////////////   //
    //Método para guardar una universidad introduciendo los campos necesarios
    //Se verifican los cambios y se inicia una conexión para guardar la universidad
    private void guardarUniversidad() throws HeadlessException {
        Object valorSpinner = spinnerCodigo.getValue();
        Session session = null;
        //Verificación de campos vacíos.
        //Si alguno de los campos solicitados está vacío, mostramos un mensaje de aviso.
        if (campoNombre.getText().equals("") || campoProvincia.getText().equals("") || grupoBotonesPrivada.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Debes de rellenar TODOS los campos");
        } else {
            //Almacenamos el estado del botón
            boolean privada = radioButtonSI.isSelected();
            try {
                //Abrimos la conexión e iniciamos la transacción
                session = HibernateUtil.getSessionFactory().openSession();
                session.beginTransaction();
                //Almacenamos el valor del spinner en un int para poder pasarlo como parámetro
                int codigoUniversidad = (int) valorSpinner;
                //Generamos la consulta
                String hql = "FROM Universidad u WHERE u.codigo = :codigo";
                Query consulta = session.createQuery(hql);
                consulta.setParameter("codigo", codigoUniversidad);

                // Si el código ya existe, mostramos un mensaje
                if (!consulta.list().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "El código " + codigoUniversidad + " ya está asignado a otra universidad. Introduce un código diferente.");
                } else {

                    //Instanciamos un objeto Universidad con los datos obtenidos
                    Universidad uni = new Universidad((int) valorSpinner, campoNombre.getText(),
                            campoProvincia.getText(), privada, null);
                    //Guardamos la nueva universidad
                    session.save(uni);
                    //Indicamos que todo ha terminado
                    session.getTransaction().commit();
                    //Mostramos un mensaje al usuario
                    JOptionPane.showMessageDialog(this, "Universidad " + uni.getNombre() + " almacenada en la base de datos");
                }
            } catch (HibernateException he) {
                System.out.println("Error Hibernate: " + he.getMessage());
                if (session.getTransaction() == null) {
                    //Si hay algún error en la transacción
                    //Hacemos un rollBack para deshacer los cambios    
                    session.getTransaction().rollback();
                }
                JOptionPane.showMessageDialog(this, "No se ha podido añadir la universidad");
            } finally {
                if (session != null) {
                    session.close(); //Cerramos la sesión
                }
            }
        }

    }

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        //Cerramos la ventana
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaUniversidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoProvincia;
    private javax.swing.ButtonGroup grupoBotonesPrivada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioButtonNO;
    private javax.swing.JRadioButton radioButtonSI;
    private javax.swing.JSpinner spinnerCodigo;
    // End of variables declaration//GEN-END:variables
}
